modGroup=deez.togglesneak
modVersion=3.3.8
modBaseName=togglesneak
mcVersion=1.21.11
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric settings
loom_version=1.15-SNAPSHOT
fabric_version=0.141.3+1.21.11
fabric_loader_version=0.18.6

# Neoforge settings
neoforge_moddev=2.0.141
neoforge_version=21.11.42